AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 40

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 400

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

